### ISSUE TITLE
“ID was called incorrectly” when Featured Products widget is in use

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-connect-woocommerce#10]
I see this notice when viewing a page displaying the Featured Products widget:

`ID was called incorrectly. Product properties should not be accessed directly. Backtrace: require('index.php'), require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/genesis/index.php'), genesis, do_action('genesis_after_content'), WP_Hook->do_action, WP_Hook->apply_filters, genesis_get_sidebar, get_sidebar, locate_template, load_template, require_once('/themes/genesis/sidebar.php'), do_action('genesis_sidebar'), WP_Hook->do_action, WP_Hook->apply_filters, genesis_do_sidebar, dynamic_sidebar, WP_Widget->display_callback, Gencwooc_Featured_Products->widget, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.)`

### Widget settings
<img width="336" alt="widgets_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/30716299-6f1f933a-9f11-11e7-9d46-9f5bcca1a854.png">

Solved by changing this:

`woocommerce_template_loop_add_to_cart( $product->ID );`

To this:

`woocommerce_template_loop_add_to_cart( $product->get_id() );`

In `plugins/genesis-connect-woocommerce/widgets/woocommerce-featured-widgets.php`

**Comment by nickcernis** [comment]
To test:

- Ensure `wp-config.php` contains `define( 'WP_DEBUG', true);`
- Activate Genesis Sample.
- Add this to functions.php: `add_theme_support( 'gencwooc-featured-products-widget' );`
- Add a Genesis Featured Products widget to the sidebar showing at least one product.
- Visit a post or page that displays that sidebar.

Confirm:
- [ ] Featured Products widget appears as expected.
- [ ] This error does not appear on screen or in logs:

```PHP Fatal error:  Uncaught Error: Call to a member function get_id() on string in 
/wpdev/wp-content/themes/genesis/includes/Layout/Manager.php:203 
```

**Comment by swa433** [comment]
@nickcernis Confirmed +1

**Environment:**
WordPress:
Version: 4.9.7

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Genesis Sample (active theme):
Version: 2.6.0

WooCommerce:
Version: 3.4.3

Genesis Connect for WooCommerce:
Version: 0.9.10
Issue reproducible!

Genesis Connect for WooCommerce:
Version: 0.9.11 ( https://github.com/copyblogger/genesis-connect-woocommerce )
Issue fixed!

**Comment by nickcernis** [comment]
Thanks so much for your help with these, Waqar!
