### ISSUE TITLE
Missing do_action( 'woocommerce_shop_loop' ); & do_action( 'woocommerce_no_products_found' ); in genesiswooc_content_product()

### ISSUE THREAD

**Issue by carasmo** [copyblogger/genesis-connect-woocommerce#12]
in the genesiswooc_content_product(), when you compare Woo's [archive-product.php](https://github.com/woocommerce/woocommerce/blob/a2e0535f2f501d777da0069419ed8ddc86293196/templates/archive-product.php) it's missing.

`do_action( 'woocommerce_shop_loop' );`

and

`do_action( 'woocommerce_no_products_found' );`

**Comment by carasmo** [comment]
Works fine when I added them in my install.

**Comment by dreamwhisper** [comment]
Resolved with https://github.com/copyblogger/genesis-connect-woocommerce/commit/376a864d89d82efc166cd26088864532a4390475
