### ISSUE TITLE
0.9.10 Fatal error

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-connect-woocommerce#16]
We have several reports of a blank shop page and fatal error introduced after 0.9.10:

- https://wordpress.org/support/topic/latest-gcw-0-9-10-displays-blank-shop-page/
- https://wordpress.org/support/topic/fatal-error-2795/

```
Fatal error: Call to undefined function wc_get_loop_prop() in 
/home/shannast/public_html/wp-content/plugins/genesis-connect-woocommerce/
lib/template-loader.php on line 268
```

```
2018-02-01T02:12:44+00:00..Error: Call to undefined function wc_get_loop_prop() in ..wp-content/plugins/genesis-connect-woocommerce/lib/template-loader.php:268
Stack trace:
#0./genesis-connect-woocommerce/templates/archive-product.php(88): genesiswooc_content_product()
#1./wp-includes/class-wp-hook.php(286): genesiswooc_archive_product_loop('')
#2  wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 ../themes/genesis/lib/framework.php(38): do_action('genesis_before_...')
#5 /genesis-connect-woocommerce/templates/archive-product.php(94): genesis()
...
```

Seems related to https://github.com/woocommerce/woocommerce/issues/18683 but I cannot see that Genesis Connect adds theme support after init.

**Comment by nickcernis** [comment]
My guess is reporters did not update WooCommerce to 3.3.0 before updating Genesis Connect to 0.9.10, as wc_get_loop_prop() is declared in 3.3.0 and we don't check if the function exists before using it in G Connect.

**Comment by dreamwhisper** [comment]
> My guess is reporters did not update WooCommerce to 3.3.0 before updating Genesis Connect to 0.9.10.

Yeah, WooCommerce was reduced back to 3.2.6 on https://wordpress.org/plugins/woocommerce/ so now Genesis Connect users get the update notice, but can't see that WooCommerce also had an update.

**Comment by nathanrice** [comment]
So, they introduce breaking changes that render themes with custom templates unusable, and the solution they recommended is to update your templates to use the 3.3 ones, which uses a 3.3-only function ... then they make 3.3 unavailable?

I know releasing updates is a hard job more than most, but man, I hope they get this figured out soon.

**Comment by nickcernis** [comment]
They now have an announcement at the top of https://woocommerce.com/2018/01/whats-new-woocommerce-3-3/.

> We’ve delayed tagging WooCommerce 3.3 as stable while we resolve some template changes affecting popular themes. In the meantime, you can read all about the new features in 3.3 coming soon below.

“We’ve delayed tagging WooCommerce 3.3 as stable” is perhaps not the full story, but I expect we'll see 3.3.1 in its place soon enough.

**Comment by Codewryter** [comment]
My shop page was empty on a client site after upgrade. Where can I download Genesis Connect version 0.9.9? Thanks so much.

**Comment by Codewryter** [comment]
I found the download. Sorry to bug here...

**Comment by FawadNL** [comment]
We had the same issue today, but reversed the Genesis Connect update with a backup.

**Comment by nickcernis** [comment]
No sign of a new 3.3 release yet. The 3.3.1 milestone is at https://github.com/woocommerce/woocommerce/milestone/113 with no due date.

@dreamwhisper @nathanrice Should we set the stable tag to 0.9.9 again until the 3.3 release? It looks like I was too optimistic above, and we're seeing a stream of support requests from people updating to 0.9.10 and having blank shop and category pages.

**Comment by dreamwhisper** [comment]
@nickcernis It is on my agenda to talk with @nathanrice this morning after reviewing tickets. I saw last night that their 3.3.1 milestone is now planned for sometime next week, which we weren't expecting. See https://woocommerce.wordpress.com/2018/02/01/woocommerce-3-3-1-status-update/

**Comment by nickcernis** [comment]
WooCommerce 3.3.1 is out: https://wordpress.org/plugins/woocommerce/

I tested it with Genesis Connect 0.9.10 and all seems well so far (no fatal errors, layout seems correct), in case we want to bump the stable version again.

**Comment by dreamwhisper** [comment]
@nathanrice We can re-release 0.9.10 at this point. It also fixes a deprecation notice.

**Comment by nathanrice** [comment]
Done.

**Comment by dreamwhisper** [comment]
Thanks @nathanrice!
