### ISSUE TITLE
Add WooCommerce Version Check

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-connect-woocommerce#18]
Add WooCommerce version check in plugin header.

See https://woocommerce.wordpress.com/2017/08/28/new-version-check-in-woocommerce-3-2/

**Comment by dreamwhisper** [comment]
![woo](https://user-images.githubusercontent.com/1271053/36153457-4e64b13c-109c-11e8-99be-b07f55927bb3.png)

**Comment by nickcernis** [comment]
Added Woo version support as:

- WC requires at least: 3.3.0
- WC tested up to: 3.4.0

Also bumped tested WP version to 4.9.

**Comment by swa433** [comment]
@nickcernis Confirmed +1

- WooCommerce Version Check works.

1. Screenshot with Genesis Connect for WooCommerce - Version: 0.9.10: http://nimb.ws/QxCZMs
2. Screenshot with Genesis Connect for WooCommerce - Version: 0.9.11: http://nimb.ws/9mB8bR

- "Tested up to" also updated.

**Environment:**
WordPress:
Version: 4.9.7

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Genesis Sample (active theme):
Version: 2.6.0

WooCommerce:
Version: 3.4.3

Genesis Connect for WooCommerce:
Version: 0.9.10
Issue reproducible!

Genesis Connect for WooCommerce:
Version: 0.9.11 ( https://github.com/copyblogger/genesis-connect-woocommerce )
Issue fixed!
