### ISSUE TITLE
ss_do_one_sidebar deprecated notice

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-connect-woocommerce#19]
We intended to fix the deprecated notice for simple sidebars, but it looks like we may not have opened an issue.

>Notice : ss_do_one_sidebar is deprecated since version 2.1.0! Use dynamic_sidebar () with sidebars_widget filter instead. in /public_html/wp-includes/functions.php on line 3839

https://github.com/copyblogger/genesis-simple-sidebars/issues/22#issuecomment-285801024

**Comment by nickcernis** [comment]
To test:

## Setup
1. Activate a theme with two sidebars, such as Magazine Pro.
2. Activate Genesis Simple Sidebars and create two custom sidebars.
3. Add a widget to those sidebars.
4. Activate WooCommerce, create a shop page, and configure the shop page at WooCommerce → Settings → Products.
5. Edit the Shop page and assign a custom sidebar to the Primary and Secondary sidebar areas.

## Confirm that:
- [ ] No deprecation warnings in logs when viewing a page with a custom sidebar.
- [ ] Shop page shows both custom sidebars you've set.
- [ ] Shop page shows regular sidebars if “Default” is selected as the sidebar.
- [ ] Shop page shows regular sidebars if Genesis Simple Sidebars is inactive.
- [ ] Regular pages show default sidebars if set.
- [ ] Regular pages show custom sidebars if set.
- [ ] Regular pages show default sidebars if Genesis Simple Sidebars is inactive.

**Comment by swa433** [comment]
@nickcernis Confirmed +1

- [x] No deprecation warnings in logs when viewing a page with a custom sidebar.
- [x] Shop page shows both custom sidebars you've set.
- [x] Shop page shows regular sidebars if “Default” is selected for each sidebar.
- [x] Shop page shows regular sidebars if Genesis Simple Sidebars is inactive.
- [x] Regular pages show default sidebars if set.
- [x] Regular pages show custom sidebars if set.
- [x] Regular pages show default sidebars if Genesis Simple Sidebars is inactive.


**Environment:**
WordPress:
Version: 4.9.7

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Magazine Pro (active theme):
Version: 3.2.4

WooCommerce:
Version: 3.4.3

Genesis Simple Sidebars:
Version: 2.1.0

Genesis Connect for WooCommerce:
Version: 0.9.10
Issue reproducible!

Genesis Connect for WooCommerce:
Version: 0.9.11 ( https://github.com/copyblogger/genesis-connect-woocommerce )
Issue fixed!
