### ISSUE TITLE
Show Genesis Archive Headline and Intro Text if set 

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-connect-woocommerce#21]
We removed the Archive Headline and Intro Text on product category archives to prevent duplicate headlines in https://github.com/copyblogger/genesis-connect-woocommerce/issues/4.

We've seen comments from people who'd prefer that text to remain in place: https://wordpress.org/support/topic/product-category-pages-have-lost-their-titles/

There's a pull request here to restate the intro text: https://github.com/copyblogger/genesis-connect-woocommerce/pull/14

After discussing with @dreamwhisper, we think the pull request could be altered so that:

- WooCommerce title and description are removed by default.
- Genesis Archive Headline and Intro Text are displayed instead if set.
- If Genesis Archive Headline and Intro Text are empty, the WooCommerce product category title and category description appear. They should display within the Genesis markup so the styling is the same.

**Comment by nickcernis** [comment]
I submitted a PR for this.

To test:

1. View a product archive page such as `product-category/uncategorized/`
2. Edit the category.
3. Set a name and description.

Verify:

- [] Category name appears if Genesis Archive Headline is unset.
- [] Category description appears if Genesis Archive Intro Text is unset.
- [] Category name and description appear within Genesis markup area.
- [] Genesis Archive Headline appears in place of category name when set.
- [] Genesis Archive Intro Text appears in place of category description when set.
- [] No description appears if description and intro text are unset.

**Comment by madriverweb** [comment]
Please reinstate the Archive Intro Text regardless of what you do with title, for those of us that lost it in our sites, and because it IS better with formatting, etc., an argument someone else made. Regarding "Name", Archive Heading is better, too, because it can be longer and more descriptive without affecting the navigation (requiring additional clean-up) or the Product Category display that is better with the short "name."

**Comment by madriverweb** [comment]
I understand better now, you are planning to have Archive Headline and Intro Text override Name/Title and Description. Look forward to being able to implement this solution.

**Comment by nickcernis** [comment]
To test:

For a pass, tests should work with Genesis Sample 2.6.0 and Essence Pro 1.0.2 (which moves the archive header).

## Test 1

1. View a product archive page such as `product-category/uncategorized/`
2. Click “Edit category”.
3. Set a name and description but leave Genesis archive intro text and archive description blank:

    ![screenshot-product-category](https://user-images.githubusercontent.com/647669/42532376-017665e6-8487-11e8-8206-81550ab72936.png)

4. Save changes and visit the product category archive at `product-category/uncategorized/`

Verify:
- [ ] Category name appears if Genesis Archive Headline is unset.
- [ ] Category description appears if Genesis Archive Intro Text is unset.
- [ ] Category name and description appear within Genesis archive heading markup area.

## Test 2

1. Edit the same product category archive.
2. Set the Genesis archive intro text and archive headline
3. Save and visit the product category archive

Verify:
- [ ] Genesis Archive Headline appears in place of category name.
- [ ] Genesis Archive Intro Text appears in place of category description.

**Comment by swa433** [comment]
@nickcernis Confirmed +1

Environment:
WordPress:
Version: 4.9.7

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Essence Pro (active theme):
Version: 1.0.2

WooCommerce:
Version: 3.4.3

Genesis Connect for WooCommerce:
Version: 0.9.10
Issue reproducible!

Genesis Connect for WooCommerce:
Version: 0.9.11 ( https://github.com/copyblogger/genesis-connect-woocommerce )
Issue fixed!

**Test 1**

Verified:

- [x] Category name appears if Genesis Archive Headline is unset.
- [x] Category description appears if Genesis Archive Intro Text is unset.
- [x] Category name and description appear within Genesis archive heading markup area.

**Test 2**

Verified:

- [x] Genesis Archive Headline appears in place of category name.
- [x] Genesis Archive Intro Text appears in place of category description.
