### ISSUE TITLE
Remove structured data from templates

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-connect-woocommerce#23]
As reported at https://wordpress.org/support/topic/structured-data-problem-using-this-plugin-and-woocommerce-3-x/, WooCommerce 3 switched to JSON LD for structured data.

https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#product-schema-markup-moved-to-json-ld-format

The schema markup in our product templates therefore causes errors in Google's structured data testing tool, because WooCommerce 3 no longer outputs expected schema output in tags such as product headings:

![screen shot on 2018-02-28 at 09 38 00](https://user-images.githubusercontent.com/647669/36777845-3cc1615c-1c6b-11e8-9eca-3d1cb9073bf8.png)
 
Under Woo 2.6.14 the markup looked like this and was valid:

![screen shot on 2018-02-28 at 09 37 32](https://user-images.githubusercontent.com/647669/36777872-54d34f44-1c6b-11e8-8e67-2f12e51d2244.png)

I suggest we drop the schema markup from product templates and make WooCommerce 3 the minimum recommended compatible version.

**Comment by nickcernis** [comment]
To test:

- Visit a product page.
- Copy the source.
- Paste to https://search.google.com/structured-data/testing-tool/ and run Google's test.

Confirm:

- [ ] Product is detected, with correct data for the product.
- [ ] Product contains no errors or warnings, as below.

![structured-data-test-results](https://user-images.githubusercontent.com/647669/41276923-027f1d6a-6e26-11e8-997e-558ce939bc68.png)

**Comment by nickcernis** [comment]
Confirmed ×1 in WP.org forums:

https://wordpress.org/support/topic/schema-error-3/#post-10478384

**Comment by swa433** [comment]
@nickcernis Confirmed +1
(product is detected, with correct data & without any error/warning related to product)

**Environment:**
WordPress:
Version: 4.9.7

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Genesis Sample (active theme):
Version: 2.6.0

WooCommerce:
Version: 3.4.3

Genesis Connect for WooCommerce:
Version: 0.9.10
Issue reproducible!

Genesis Connect for WooCommerce:
Version: 0.9.11 ( https://github.com/copyblogger/genesis-connect-woocommerce )
Issue fixed!
