### ISSUE TITLE
Can't use add_theme_support in theme to specify woo image sizes

### ISSUE THREAD

**Issue by calliaweb** [copyblogger/genesis-connect-woocommerce#26]
According to https://docs.woocommerce.com/document/image-sizes-theme-developers/ I should be able to add the following to specify default image sizes in my theme for WooCommerce

`add_theme_support( 'woocommerce', array(
'thumbnail_image_width' => 200,
'gallery_thumbnail_image_width' => 100,
'single_image_width' => 500,
) );`

However with Genesis Connect WooCommerce it doesn't appear to work. With the above code it is expected that the option to change the image sizes is removed from the customiser but it is not. If I deactivate Genesis Connect WooCommerce then the changing image sizes from the customiser is removed (but I couldn't test further because other things then failed because I didn't have the plugin active).

I *think* that the add_theme_support declaration in the plugin (without the image sizes) takes precedent over mine in my theme.

I can't think of a solution other than to use the woocommerce_get_image_size_ filter to change the image sizes, which is not recommended.

**Comment by dreamwhisper** [comment]
@calliaweb Try hooking the function like this:

```php
add_action( 'after_setup_theme', 'child_woocommerce_image_dimensions_after_theme_setup', 11 );
function child_woocommerce_image_dimensions_after_theme_setup() {

	add_theme_support(
		'woocommerce', array(
			'thumbnail_image_width'         => 200,
			'gallery_thumbnail_image_width' => 100,
			'single_image_width'            => 500,
		)
	);

}
```

That should add it after the plugin does.

**Comment by calliaweb** [comment]
Thank you @dreamwhisper that works!
