### ISSUE TITLE
Allow network activation on multisite

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-connect-woocommerce#27]
The plugin currently has no effect when network activated due to this line:

~~~php
if ( ! in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) )
~~~

We see support requests about this as a result.

The suggestion at https://wordpress.org/support/topic/patch-no-support-for-multisite/ solves this, but may require amending and further testing.

**Comment by swa433** [comment]
@nickcernis Confirmed +1

Environment:
WordPress:
Version: 4.9.7

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Genesis Sample (active theme):
Version: 2.6.0

WooCommerce:
Version: 3.4.3

Genesis Connect for WooCommerce:
Version: 0.9.10
Issue reproducible!

Genesis Connect for WooCommerce:
Version: 0.9.11 ( https://github.com/copyblogger/genesis-connect-woocommerce )
Issue fixed!
