### ISSUE TITLE
Add widget back

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-connect-woocommerce#28]
Need to add these lines back to allow the widget to load:

https://github.com/copyblogger/genesis-connect-woocommerce/blob/1c57ff712be4db22a97701108a4ca6323796665a/genesis-connect-woocommerce.php#L88-L90

**Comment by nickcernis** [comment]
To test:

1. Activate Genesis Sample.
2. Add this line to `functions.php`: `add_theme_support( 'gencwooc-featured-products-widget' );`

Confirm:
- [ ] The Genesis Featured Product widget is available from Appearance → Widgets

**Comment by swa433** [comment]
@nickcernis Confirmed +1

**Environment:**
WordPress:
Version: 4.9.7

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Genesis Sample (active theme):
Version: 2.6.0

WooCommerce:
Version: 3.4.3

Genesis Connect for WooCommerce:
Version: 0.9.10
Issue reproducible!

Genesis Connect for WooCommerce:
Version: 0.9.11 ( https://github.com/copyblogger/genesis-connect-woocommerce )
Issue fixed!
