### ISSUE TITLE
Templates ignore 'Default layout in theme settings'

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-connect-woocommerce#29]
Reproducible with Genesis Sample by:

1. Editing the shop page.

2. Selecting “Default Layout set in Theme Settings”:
    ![edit_page_ _test_site_ _wordpress](https://user-images.githubusercontent.com/647669/40565797-37e8f4fa-606e-11e8-9a10-ab3e9b9c3bab.jpg)

3. Choosing the full-width layout as the site default in Genesis → Theme Settings.

- Expected: shop page uses full-width layout.
- Observed: shop page uses content-sidebar layout.

**Comment by dreamwhisper** [comment]
I knew I wasn’t crazy  :)

**Comment by nickcernis** [comment]
Ready for testing:

## Setup
1. Configure the shop page at WooCommerce → Settings → Products.

## Confirm
- [ ] Shop page uses default Genesis site layout if “default layout set in theme settings” is chosen.
- [ ] Shop page uses selected layout otherwise.

**Comment by swa433** [comment]
@nickcernis Confirmed +1
("default" and the "selected" layouts, both work with the planned release)

**Environment:**
WordPress:
Version: 4.9.7

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Genesis Sample (active theme):
Version: 2.6.0

WooCommerce:
Version: 3.4.3

Genesis Connect for WooCommerce:
Version: 0.9.10
Issue reproducible!

Genesis Connect for WooCommerce:
Version: 0.9.11 ( https://github.com/copyblogger/genesis-connect-woocommerce )
Issue fixed!
