### ISSUE TITLE
woocommerce_get_page_id deprecated in WooCommerce 3

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-connect-woocommerce#3]
Genesis Connect for WooCommerce 0.9.9 generates deprecation notices with WooCommerce 3.0:

~~~
Notice: woocommerce_get_page_id is deprecated since version 3.0! 
Use wc_get_page_id instead.
~~~

`woocommerce_get_page_id()` is currently used in:

- sp-plugins-integration/genesis-simple-menus.php
- sp-plugins-integration/genesis-simple-sidebars.php
- lib/breadcrumb.php

One way to reproduce:
1. Activate Genesis Sample, Genesis Connect 0.9.9, and WooCommerce 3.0.
2. Enable breadcrumbs on Single Posts in Genesis → Theme Settings.
3. Visit any product page with WP debug mode on.

You'll see the deprecation notice above the breadcrumbs and in logs.

[wc_get_page_id](https://docs.woocommerce.com/wc-apidocs/function-wc_get_page_id.html) has been available since Woo 2.6, so we could update to that without raising the minimum required version of WooCommerce to 3.0.

**Comment by JiveDig** [comment]
Just came to make sure an issue was open for this. Thanks yall.

**Comment by carasmo** [comment]
I made a pull request for this. It's July 28, WooCommerce 3.0 has been out for a while. All SP Child themes support WooCommerce, please correct this and the double titles on Archive pages (also in the pull request). https://github.com/copyblogger/genesis-connect-woocommerce/pull/8

**Comment by bgardner** [comment]
@nathanrice

**Comment by carasmo** [comment]
Any updates?

**Comment by nathanrice** [comment]
A small maintenance update is forthcoming. We need to test internally, but it should be too long.

**Comment by carasmo** [comment]
I updated from this repo instead of WordPress but I still get the double title on the taxonomy pages.

**Comment by carasmo** [comment]
Thank you!
