### ISSUE TITLE
Incorrect template when WooCommerce shop page is not set

### ISSUE THREAD

**Issue by timothyjensen** [copyblogger/genesis-connect-woocommerce#31]
If the WooCommerce shop page is not set Genesis Connect for WooCommerce will serve the wrong template.

To reproduce, go to WooCommerce settings -> Products, remove the shop page, and save the settings.  Next, view any page, which will be blank because GCW is serving the `archive-product` template.

**Comment by nickcernis** [comment]
Thanks for the find and the fix, Tim!
