### ISSUE TITLE
Product oembeds fail to load

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-connect-woocommerce#34]
As reported at https://wordpress.org/support/topic/problems-with-oembed-of-woocommerce-products/, WooCommerce product oembeds load only the quote and not the full product preview.

## To reproduce

1. Add the full URL of any WooCommerce product to page content, on its own line.

## Expected

<img width="666" alt="test_product_embed" src="https://user-images.githubusercontent.com/647669/42223722-be5ad368-7ed8-11e8-8b85-4bd7466b53aa.png">

## Observed

<img width="555" alt="test_product_embed" src="https://user-images.githubusercontent.com/647669/42223741-cb120234-7ed8-11e8-8462-6df147bc9f3b.png">

I have an incoming fix for this to bypass template loading for embed requests.

**Comment by nickcernis** [comment]
To test:

1. Add the full URL of any WooCommerce product to page content, on its own line.

2. Confirm the product appears embedded in the page, as pictured above.

**Comment by nickcernis** [comment]
Confirmed ×1 in WP forums: https://wordpress.org/support/topic/problems-with-oembed-of-woocommerce-products/#post-10459066

**Comment by swa433** [comment]
@nickcernis Confirmed +1

**Environment:**
WordPress:
Version: 4.9.7

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Genesis Sample (active theme):
Version: 2.6.0

WooCommerce:
Version: 3.4.3

Genesis Connect for WooCommerce:
Version: 0.9.10
Issue reproducible!

Genesis Connect for WooCommerce:
Version: 0.9.11 ( https://github.com/copyblogger/genesis-connect-woocommerce )
Issue fixed!
