### ISSUE TITLE
Add Plugin to WP Packagist

### ISSUE THREAD

**Issue by jasperf** [copyblogger/genesis-connect-woocommerce#61]
**Is your feature request related to a problem? Please describe.**
Installing Genesis Connect for WooCommerce as Composer package or WP Packagist package not possible

**Describe the solution you'd like**
Add this plugin to https://wpackagist.org/ by updating `composer.json`. 

1. Add the WP Packagist repository to your `composer.json`
2. Add the desired plugins and themes to your requirements using `wpackagist-plugin` or `wpackagist-theme` as the vendor name.
3. Run `$ composer.phar update`
4. Packages are [installed](https://github.com/composer/installers) to `wp-content/plugins/` or `wp-content/themes/` (unless otherwise specified by installer-paths)

**NB** Plugin needs to be in WordPress Subversion repository

**Describe alternatives you've considered**
Composer VCS package, but in image I often bump into proper loading issues.

**Comment by nickcernis** [comment]
Genesis Connect for WooCommerce already appears in WP Packagist and should be available to install via your composer.json: https://wpackagist.org/search?q=genesis-connect-woocommerce

**Comment by jasperf** [comment]
Darn it. I looked for Genesis Connect and did not see it. But added `genesis-connect-woocommerce` does. Double checked again and it is there now. Also when looking for Genesis Connect. So must have misspelled. My bad. Thanks for getting back on this @nickcernis .

**Comment by nickcernis** [comment]
No problem, @jasperf, the search feature there is pretty fussy — you have to give it the exact plugin slug!
