### ISSUE TITLE
Widget theme support

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-connect-woocommerce#9]
@cjkoepke @nathanrice when I enabled the widget in the theme with `add_theme_support( 'gencwooc-featured-products-widget' );`, I got a series of these on admin pages with debug on:

>Notice: Undefined variable: width in wp-content/plugins/genesis-connect-woocommerce/widgets/woocommerce-featured-widgets.php on line 225

>Notice: Undefined variable: height in wp-content/plugins/genesis-connect-woocommerce/widgets/woocommerce-featured-widgets.php on line 225

**Comment by nickcernis** [comment]
Confirmed notices no longer present.
